@startuml
actor user
participant "Model" as M
participant "TimetableManager" as TM
participant "Timetable" as T
participant "Mod" as Mo


User -> M: execute("addModToTimetable timetableName modCodeOrName")
activate M
M -> TM: check if timetable exists
activate TM
TM -> M: timetable found or not found
deactivate TM
alt Timetable not found
    M -> User: "Timetable not found."
    deactivate M
    return
end

M -> TM: addModToTimetable(timetableName, mod)
activate TM
TM -> T: addMod(mod)
activate T
T -> M: timetable updated
deactivate T
M -> User: "Mod added to timetable."
deactivate M

User -> M: execute("removeModFromTimetable timetableName modCodeOrName")
activate M
M -> TM: check if timetable exists
activate TM
TM -> M: timetable found or not found
deactivate TM
alt Timetable not found
    M -> User: "Timetable not found."
    deactivate M
    return
end

M -> TM: removeModFromTimetable(timetableName, mod)
activate TM
TM -> T: removeMod(mod)
activate T
T -> M: timetable updated
deactivate T
M -> User: "Mod removed from timetable."
deactivate M

@enduml
